                     Python Assignment: Data Structures, Functions, Numpy & Pandas                .

Assignment Questions

Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [170]:
list = [4,5,67,87,2]

In [171]:
list

[4, 5, 67, 87, 2]

In [174]:
#append operation
list.append(22)


In [175]:
list

[4, 5, 67, 87, 2, 22, 22]

In [81]:
#extend operation
list.extend(["Ian"])
list

[4, 5, 67, 87, 2, 22, 'Ian']

In [82]:
#insert operation
list.insert(3,"Eva")
list

[4, 5, 67, 'Eva', 87, 2, 22, 'Ian']

In [83]:
#remove operation
list.remove(2)
list

[4, 5, 67, 'Eva', 87, 22, 'Ian']

In [84]:
#pop operation
list.pop(5)
list

[4, 5, 67, 'Eva', 87, 'Ian']

In [85]:
#index operation
list.index("Eva")

3

In [86]:
#sort operation
list1 = [3,67,24,87,1]
list1.sort()
list1

[1, 3, 24, 67, 87]

In [87]:
#reverse operation
list1.reverse()
list1

[87, 67, 24, 3, 1]

In [88]:
#Clear operation
list1.clear()

In [89]:
list1

[]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [90]:
Std = ("Eva","Ian","Ram")
Std

('Eva', 'Ian', 'Ram')

In [91]:
Std.insert(2,"Ayana")

AttributeError: 'tuple' object has no attribute 'insert'

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
myset = {3,5,65,3,43,7,8,98,8,7}
print("Set :",myset)

Set : {65, 98, 3, 5, 7, 8, 43}


4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
dict = {"name":"Eva","age":22,"city":"tumakuru" }
print(dict)

{'name': 'Eva', 'age': 22, 'city': 'tumakuru'}


In [ ]:
dict.update({"age":23})
dict

{'name': 'Eva', 'age': 23, 'city': 'tumakuru'}

In [ ]:
dict["email"] = "evian@gmail.com"
print(f"final dictionary is : {dict}")

final dictionary is : {'name': 'Eva', 'age': 23, 'city': 'tumakuru', 'email': 'evian@gmail.com'}


5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age = int(input("Enter your age :"))
if age >= 18:
    print("You are eligible to Vote")
else:
    print("Sorry!.. you are not eligible to Vote")

You are eligible to Vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [ ]:
Marks = int(input("Enter your marks:"))

print(Marks)

if Marks >= 90:
    print("Congratulations your grade is : A")
elif 79 <= Marks <= 89:
    print("Congratulations your grade is : B") 
elif 50 <= Marks <= 74:
    print("You can do better your grade is : C")
else:
    print("Better luck next time your Fail")


98
Congratulations your grade is : A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num = int(input("Enter your marks:"))

if num > 0:
    if num % 2 == 0:
        print("The number is Positive and Even ")
    else:
        print("The number is Positive but Odd")
elif num == 0:
    print("The number iis Zero")
else:
    print("The number is Negative")

The number is Positive but Odd


Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [2]:
import pandas as pd
import numpy  as np

In [9]:
# 1. Creating a scalar using np.array(5)
scalar = np.array(5)
print("Scalar:", scalar)

Scalar: 5


In [10]:
# 2. Creating a 1D array with values 1 to 5
array_1d = np.arange(1, 6)
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [ ]:
# 3. Creating a 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.arange(10, 61, 10).reshape(2, 3)
print("2D Array (2x3):\n", array_2d)

2D Array (2x3):
 [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [7]:
array = np.random.randint(0, 101, size=(4, 4))
print(array)

[[26 12 35 72]
 [73 19 98 40]
 [ 4  5 17  5]
 [72 50 18 92]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
array_3x3 = np.arange(1, 10).reshape(3, 3)
print("NumPy array:")
print(array_3x3)

Original NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
df = pd.DataFrame(array_3x3, columns=['A', 'B', 'C'])
print("\nPandas DataFrame is:")
print(df)


Pandas DataFrame is:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [151]:
import pandas as pd

data = {
    "Name": ["Alice", "Ian", "Charlie", "Alice", "Eva", "Frank", "Grace", "Hannah", "Jungkook", "Kenho"],
    "Age": [25, 30, 22, 25, 35, 40, 27, 23, 26, 25],
    "City": ["Delhi", "Mumbai", "Chennai", "Delhi", "Bangalore", "Pune", "Hyderabad", "Ahmedabad", "Busan", "Seoul"],
    "Salary": [50000, 60000, 45000, 50000, 70000, 80000, 48000, 47000, 90000, None]
}

df = pd.DataFrame(data)

df


Name  Age       City   Salary
0     Alice   25      Delhi  50000.0
1       Ian   30     Mumbai  60000.0
2   Charlie   22    Chennai  45000.0
3     Alice   25      Delhi  50000.0
4       Eva   35  Bangalore  70000.0
5     Frank   40       Pune  80000.0
6     Grace   27  Hyderabad  48000.0
7    Hannah   23  Ahmedabad  47000.0
8  Jungkook   26      Busan  90000.0
9     Kenho   25      Seoul      NaN

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes


In [153]:
df.describe()

Age        Salary
count  10.000000      9.000000
mean   27.800000  60000.000000
std     5.672546  16347.782724
min    22.000000  45000.000000
25%    25.000000  48000.000000
50%    25.500000  50000.000000
75%    29.250000  70000.000000
max    40.000000  90000.000000

In [ ]:
df.loc[:,["Name","City"]]

Name       City
0     Alice      Delhi
1       Ian     Mumbai
2   Charlie    Chennai
3     Alice      Delhi
4       Eva  Bangalore
5     Frank       Pune
6     Grace  Hyderabad
7    Hannah  Ahmedabad
8  Jungkook      Busan
9     Kenho      Seoul

In [155]:
df.iloc[:9,[0,2]]

Name       City
0     Alice      Delhi
1       Ian     Mumbai
2   Charlie    Chennai
3     Alice      Delhi
4       Eva  Bangalore
5     Frank       Pune
6     Grace  Hyderabad
7    Hannah  Ahmedabad
8  Jungkook      Busan

In [156]:
df.drop(["City"], axis=1,inplace=True)

In [157]:
df

Name  Age   Salary
0     Alice   25  50000.0
1       Ian   30  60000.0
2   Charlie   22  45000.0
3     Alice   25  50000.0
4       Eva   35  70000.0
5     Frank   40  80000.0
6     Grace   27  48000.0
7    Hannah   23  47000.0
8  Jungkook   26  90000.0
9     Kenho   25      NaN

In [158]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [159]:
df

Name  Age   Salary
0     Alice   25  50000.0
1       Ian   30  60000.0
2   Charlie   22  45000.0
3     Alice   25  50000.0
4       Eva   35  70000.0
5     Frank   40  80000.0
6     Grace   27  48000.0
7    Hannah   23  47000.0
8  Jungkook   26  90000.0
9     Kenho   25      NaN

In [ ]:
df.isna().sum() # finding the missing values / None

Name      0
Age       0
Salary    1
dtype: int64

In [162]:
mean_salary = df["Salary"].mean()

In [ ]:
df["Salary"] = df["Salary"].fillna(mean_salary) # fill the missing values with the mean in Salary column

In [168]:
df

Name  Age   Salary
0     Alice   25  50000.0
1       Ian   30  60000.0
2   Charlie   22  45000.0
3     Alice   25  50000.0
4       Eva   35  70000.0
5     Frank   40  80000.0
6     Grace   27  48000.0
7    Hannah   23  47000.0
8  Jungkook   26  90000.0
9     Kenho   25  60000.0